// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_walk_TMBExports
#include <TMB.hpp>
#include "GammaNLL.hpp"
#include "NormalNLL.hpp"
#include "ctmc_hmm.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "ctmc_hmm") {
    return ctmc_hmm(this);
  } else if(model == "GammaNLL") {
      return GammaNLL(this);
  } else if(model == "NormalNLL") {
      return NormalNLL(this);
  } else {
      Rf_error("Unknown model.");
  }
  return 0;
}
