// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_walk_RCPPEXPORTS_H_GEN_
#define RCPP_walk_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace walk {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("walk", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("walk", "_walk_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in walk");
            }
        }
    }

    inline arma::sp_mat sp_mat_div(const arma::sp_mat X, const arma::sp_mat Y) {
        typedef SEXP(*Ptr_sp_mat_div)(SEXP,SEXP);
        static Ptr_sp_mat_div p_sp_mat_div = NULL;
        if (p_sp_mat_div == NULL) {
            validateSignature("arma::sp_mat(*sp_mat_div)(const arma::sp_mat,const arma::sp_mat)");
            p_sp_mat_div = (Ptr_sp_mat_div)R_GetCCallable("walk", "_walk_sp_mat_div");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sp_mat_div(Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(Y)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::sp_mat >(rcpp_result_gen);
    }

    inline arma::vec stat_dist(const arma::sp_mat& Q) {
        typedef SEXP(*Ptr_stat_dist)(SEXP);
        static Ptr_stat_dist p_stat_dist = NULL;
        if (p_stat_dist == NULL) {
            validateSignature("arma::vec(*stat_dist)(const arma::sp_mat&)");
            p_stat_dist = (Ptr_stat_dist)R_GetCCallable("walk", "_walk_stat_dist");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_stat_dist(Shield<SEXP>(Rcpp::wrap(Q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec logit(const arma::vec& x, const double& L = 0.0, const double& U = 0.0) {
        typedef SEXP(*Ptr_logit)(SEXP,SEXP,SEXP);
        static Ptr_logit p_logit = NULL;
        if (p_logit == NULL) {
            validateSignature("arma::vec(*logit)(const arma::vec&,const double&,const double&)");
            p_logit = (Ptr_logit)R_GetCCallable("walk", "_walk_logit");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_logit(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(L)), Shield<SEXP>(Rcpp::wrap(U)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec soft_plus(const arma::vec& x, const double& a = 1.0) {
        typedef SEXP(*Ptr_soft_plus)(SEXP,SEXP);
        static Ptr_soft_plus p_soft_plus = NULL;
        if (p_soft_plus == NULL) {
            validateSignature("arma::vec(*soft_plus)(const arma::vec&,const double&)");
            p_soft_plus = (Ptr_soft_plus)R_GetCCallable("walk", "_walk_soft_plus");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_soft_plus(Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(a)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::vec hard_plus(const arma::vec& x) {
        typedef SEXP(*Ptr_hard_plus)(SEXP);
        static Ptr_hard_plus p_hard_plus = NULL;
        if (p_hard_plus == NULL) {
            validateSignature("arma::vec(*hard_plus)(const arma::vec&)");
            p_hard_plus = (Ptr_hard_plus)R_GetCCallable("walk", "_walk_hard_plus");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_hard_plus(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

    inline arma::sp_mat clip_Q(const arma::sp_mat& Q, const double& clip) {
        typedef SEXP(*Ptr_clip_Q)(SEXP,SEXP);
        static Ptr_clip_Q p_clip_Q = NULL;
        if (p_clip_Q == NULL) {
            validateSignature("arma::sp_mat(*clip_Q)(const arma::sp_mat&,const double&)");
            p_clip_Q = (Ptr_clip_Q)R_GetCCallable("walk", "_walk_clip_Q");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_clip_Q(Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(clip)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::sp_mat >(rcpp_result_gen);
    }

    inline arma::mat phi_exp_lnG(const arma::rowvec& v, const arma::sp_mat& Q, double t, double prec) {
        typedef SEXP(*Ptr_phi_exp_lnG)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_phi_exp_lnG p_phi_exp_lnG = NULL;
        if (p_phi_exp_lnG == NULL) {
            validateSignature("arma::mat(*phi_exp_lnG)(const arma::rowvec&,const arma::sp_mat&,double,double)");
            p_phi_exp_lnG = (Ptr_phi_exp_lnG)R_GetCCallable("walk", "_walk_phi_exp_lnG");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_phi_exp_lnG(Shield<SEXP>(Rcpp::wrap(v)), Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(prec)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::sp_mat load_Q(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const int& ns, const int& link_r = 1, const double& a_r = 1.0, const double& l_r = 0.0, const double& u_r = 0.0, const int& link_m = 1, const double& a_m = 1.0, const bool& norm = true, const double& clip = 0.0) {
        typedef SEXP(*Ptr_load_Q)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_load_Q p_load_Q = NULL;
        if (p_load_Q == NULL) {
            validateSignature("arma::sp_mat(*load_Q)(const arma::umat&,const arma::vec&,const arma::vec&,const int&,const int&,const double&,const double&,const double&,const int&,const double&,const bool&,const double&)");
            p_load_Q = (Ptr_load_Q)R_GetCCallable("walk", "_walk_load_Q");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_load_Q(Shield<SEXP>(Rcpp::wrap(from_to)), Shield<SEXP>(Rcpp::wrap(Xb_q_r)), Shield<SEXP>(Rcpp::wrap(Xb_q_m)), Shield<SEXP>(Rcpp::wrap(ns)), Shield<SEXP>(Rcpp::wrap(link_r)), Shield<SEXP>(Rcpp::wrap(a_r)), Shield<SEXP>(Rcpp::wrap(l_r)), Shield<SEXP>(Rcpp::wrap(u_r)), Shield<SEXP>(Rcpp::wrap(link_m)), Shield<SEXP>(Rcpp::wrap(a_m)), Shield<SEXP>(Rcpp::wrap(norm)), Shield<SEXP>(Rcpp::wrap(clip)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::sp_mat >(rcpp_result_gen);
    }

    inline arma::sp_mat load_Q_sde(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const arma::vec& hij, const int& ns, const double& k, const double& clip = 0.0) {
        typedef SEXP(*Ptr_load_Q_sde)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_load_Q_sde p_load_Q_sde = NULL;
        if (p_load_Q_sde == NULL) {
            validateSignature("arma::sp_mat(*load_Q_sde)(const arma::umat&,const arma::vec&,const arma::vec&,const arma::vec&,const int&,const double&,const double&)");
            p_load_Q_sde = (Ptr_load_Q_sde)R_GetCCallable("walk", "_walk_load_Q_sde");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_load_Q_sde(Shield<SEXP>(Rcpp::wrap(from_to)), Shield<SEXP>(Rcpp::wrap(Xb_q_r)), Shield<SEXP>(Rcpp::wrap(Xb_q_m)), Shield<SEXP>(Rcpp::wrap(hij)), Shield<SEXP>(Rcpp::wrap(ns)), Shield<SEXP>(Rcpp::wrap(k)), Shield<SEXP>(Rcpp::wrap(clip)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::sp_mat >(rcpp_result_gen);
    }

}

#endif // RCPP_walk_RCPPEXPORTS_H_GEN_
