// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "walk_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ctmc_n2ll_arma
double ctmc_n2ll_arma(const arma::sp_mat& L, const arma::vec& dt, int ns, const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, double p, const arma::rowvec& delta, const arma::vec& hij, double eq_prec, int link_r, double a_r, double l_r, double u_r, int link_m, double a_m, int form, double k, bool norm, double clip);
RcppExport SEXP _walk_ctmc_n2ll_arma(SEXP LSEXP, SEXP dtSEXP, SEXP nsSEXP, SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP pSEXP, SEXP deltaSEXP, SEXP hijSEXP, SEXP eq_precSEXP, SEXP link_rSEXP, SEXP a_rSEXP, SEXP l_rSEXP, SEXP u_rSEXP, SEXP link_mSEXP, SEXP a_mSEXP, SEXP formSEXP, SEXP kSEXP, SEXP normSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hij(hijSEXP);
    Rcpp::traits::input_parameter< double >::type eq_prec(eq_precSEXP);
    Rcpp::traits::input_parameter< int >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< double >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< double >::type l_r(l_rSEXP);
    Rcpp::traits::input_parameter< double >::type u_r(u_rSEXP);
    Rcpp::traits::input_parameter< int >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< double >::type a_m(a_mSEXP);
    Rcpp::traits::input_parameter< int >::type form(formSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type norm(normSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(ctmc_n2ll_arma(L, dt, ns, from_to, Xb_q_r, Xb_q_m, p, delta, hij, eq_prec, link_r, a_r, l_r, u_r, link_m, a_m, form, k, norm, clip));
    return rcpp_result_gen;
END_RCPP
}
// ctmc_predict_arma
arma::mat ctmc_predict_arma(const arma::sp_mat& L, const arma::vec& dt, int ns, const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, double p, const arma::rowvec& delta, const arma::vec& hij, double eq_prec, double trunc_tol, int link_r, double a_r, double l_r, double u_r, int link_m, double a_m, int form, double k, bool norm, double clip);
RcppExport SEXP _walk_ctmc_predict_arma(SEXP LSEXP, SEXP dtSEXP, SEXP nsSEXP, SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP pSEXP, SEXP deltaSEXP, SEXP hijSEXP, SEXP eq_precSEXP, SEXP trunc_tolSEXP, SEXP link_rSEXP, SEXP a_rSEXP, SEXP l_rSEXP, SEXP u_rSEXP, SEXP link_mSEXP, SEXP a_mSEXP, SEXP formSEXP, SEXP kSEXP, SEXP normSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hij(hijSEXP);
    Rcpp::traits::input_parameter< double >::type eq_prec(eq_precSEXP);
    Rcpp::traits::input_parameter< double >::type trunc_tol(trunc_tolSEXP);
    Rcpp::traits::input_parameter< int >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< double >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< double >::type l_r(l_rSEXP);
    Rcpp::traits::input_parameter< double >::type u_r(u_rSEXP);
    Rcpp::traits::input_parameter< int >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< double >::type a_m(a_mSEXP);
    Rcpp::traits::input_parameter< int >::type form(formSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type norm(normSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(ctmc_predict_arma(L, dt, ns, from_to, Xb_q_r, Xb_q_m, p, delta, hij, eq_prec, trunc_tol, link_r, a_r, l_r, u_r, link_m, a_m, form, k, norm, clip));
    return rcpp_result_gen;
END_RCPP
}
// sp_mat_div
arma::sp_mat sp_mat_div(const arma::sp_mat& X, const arma::sp_mat& Y);
RcppExport SEXP _walk_sp_mat_div(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(sp_mat_div(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// stat_dist
arma::vec stat_dist(const arma::sp_mat& Q);
RcppExport SEXP _walk_stat_dist(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(stat_dist(Q));
    return rcpp_result_gen;
END_RCPP
}
// logit
arma::vec logit(const arma::vec& x, double L, double U);
RcppExport SEXP _walk_logit(SEXP xSEXP, SEXP LSEXP, SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(logit(x, L, U));
    return rcpp_result_gen;
END_RCPP
}
// soft_plus
arma::vec soft_plus(const arma::vec& x, double a);
RcppExport SEXP _walk_soft_plus(SEXP xSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(soft_plus(x, a));
    return rcpp_result_gen;
END_RCPP
}
// hard_plus
arma::vec hard_plus(const arma::vec& x);
RcppExport SEXP _walk_hard_plus(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(hard_plus(x));
    return rcpp_result_gen;
END_RCPP
}
// clip_Q
arma::sp_mat clip_Q(const arma::sp_mat& Q, double clip);
RcppExport SEXP _walk_clip_Q(SEXP QSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(clip_Q(Q, clip));
    return rcpp_result_gen;
END_RCPP
}
// load_Q
arma::sp_mat load_Q(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, int ns, int link_r, double a_r, double l_r, double u_r, int link_m, double a_m, bool norm, double clip);
RcppExport SEXP _walk_load_Q(SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP nsSEXP, SEXP link_rSEXP, SEXP a_rSEXP, SEXP l_rSEXP, SEXP u_rSEXP, SEXP link_mSEXP, SEXP a_mSEXP, SEXP normSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< int >::type link_r(link_rSEXP);
    Rcpp::traits::input_parameter< double >::type a_r(a_rSEXP);
    Rcpp::traits::input_parameter< double >::type l_r(l_rSEXP);
    Rcpp::traits::input_parameter< double >::type u_r(u_rSEXP);
    Rcpp::traits::input_parameter< int >::type link_m(link_mSEXP);
    Rcpp::traits::input_parameter< double >::type a_m(a_mSEXP);
    Rcpp::traits::input_parameter< bool >::type norm(normSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(load_Q(from_to, Xb_q_r, Xb_q_m, ns, link_r, a_r, l_r, u_r, link_m, a_m, norm, clip));
    return rcpp_result_gen;
END_RCPP
}
// load_Q_sde
arma::sp_mat load_Q_sde(const arma::umat& from_to, const arma::vec& Xb_q_r, const arma::vec& Xb_q_m, const arma::vec& hij, int ns, double k, double clip);
RcppExport SEXP _walk_load_Q_sde(SEXP from_toSEXP, SEXP Xb_q_rSEXP, SEXP Xb_q_mSEXP, SEXP hijSEXP, SEXP nsSEXP, SEXP kSEXP, SEXP clipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type from_to(from_toSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_r(Xb_q_rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Xb_q_m(Xb_q_mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type hij(hijSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type clip(clipSEXP);
    rcpp_result_gen = Rcpp::wrap(load_Q_sde(from_to, Xb_q_r, Xb_q_m, hij, ns, k, clip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_walk_ctmc_n2ll_arma", (DL_FUNC) &_walk_ctmc_n2ll_arma, 20},
    {"_walk_ctmc_predict_arma", (DL_FUNC) &_walk_ctmc_predict_arma, 21},
    {"_walk_sp_mat_div", (DL_FUNC) &_walk_sp_mat_div, 2},
    {"_walk_stat_dist", (DL_FUNC) &_walk_stat_dist, 1},
    {"_walk_logit", (DL_FUNC) &_walk_logit, 3},
    {"_walk_soft_plus", (DL_FUNC) &_walk_soft_plus, 2},
    {"_walk_hard_plus", (DL_FUNC) &_walk_hard_plus, 1},
    {"_walk_clip_Q", (DL_FUNC) &_walk_clip_Q, 2},
    {"_walk_load_Q", (DL_FUNC) &_walk_load_Q, 12},
    {"_walk_load_Q_sde", (DL_FUNC) &_walk_load_Q_sde, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_walk(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
