# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_test <- function(v, Q, prec, renorm = TRUE, t2 = TRUE, checks = TRUE) {
    .Call(`_walk_my_test`, v, Q, prec, renorm, t2, checks)
}

