# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi_exp_G <- function(v, G, prec = 1.0e-8) {
    .Call(`_walk_phi_exp_G`, v, G, prec)
}

load_Q <- function(from_to, idx_q, Xb_q, off_q, ns) {
    .Call(`_walk_load_Q`, from_to, idx_q, Xb_q, off_q, ns)
}

ctmc_arma <- function(id, period, dt, cell, ns, np, from_to_q, X_q, off_q, idx_q, beta_q) {
    .Call(`_walk_ctmc_arma`, id, period, dt, cell, ns, np, from_to_q, X_q, off_q, idx_q, beta_q)
}

my_test <- function(v, Q, prec, renorm = TRUE, t2 = TRUE, checks = TRUE) {
    .Call(`_walk_my_test`, v, Q, prec, renorm, t2, checks)
}

